# Generated by Django 5.1.1 on 2024-09-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsystem',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginsystem',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
