# Generated by Django 5.0.7 on 2024-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loginsystem_access_token_loginsystem_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsystem',
            name='phone_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
