# Generated by Django 5.0.7 on 2024-09-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loginsystem_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='accuracy_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='badges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='accuracy_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='badges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
