# Generated by Django 5.0.7 on 2024-09-17 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamiflication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlevel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpoints',
            name='user',
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('difficulty', models.CharField(max_length=10)),
                ('correct_answer', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamiflication.gamecategory')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('time_taken', models.FloatField()),
                ('completed', models.BooleanField(default=False)),
                ('hints_used', models.IntegerField(default=0)),
                ('difficulty', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamiflication.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamiflication.gamecategory')),
                ('recommended_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamiflication.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_completion_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField(default=0.0)),
                ('total_games_played', models.IntegerField(default=0)),
                ('avg_time_taken', models.FloatField(default=0.0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
                ('difficulty_level', models.CharField(max_length=10)),
                ('game_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamiflication.gamecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
        migrations.DeleteModel(
            name='UserLevel',
        ),
        migrations.DeleteModel(
            name='UserPoints',
        ),
    ]
